name: remote clone


on:
  schedule:
   - cron: '5 16 * * *'  # 本地时间每天的 1:00 执行
env:
    TZ: Asia/Shanghai
jobs:
   remote_clone:
        runs-on: ubuntu-latest
        env:
                VERSION: ${{ secrets.VERSION }}
                REJECT: ${{ secrets.REJECT }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: 创建版本号
              run: |
                 if ! curl -L --silent --output ./version.sh ${{ env.VERSION}}; then
                    echo "Failed to download the file."
                    exit 1
                 fi                 
                 echo "version=$(bash version.sh)" >> $GITHUB_ENV
                 echo "## $(cat version)" >> bgcode.txt
                 echo "发布时间：$(date +'%Y-%m-%d %H:%M:%S')" >> bgcode.txt
            - name: 下载广告reject
              run: |
                if ! curl -L --silent --output ./Reject.list ${{ env.REJECT}}; then
                    echo "Failed to download the file."
                    exit 1
                fi
                # 确保备份目录存在
                if [ ! -d "./bak" ]; then
                    mkdir -p ./bak
                fi

                # 备份原始文件
                if [ -f "./filter_remote/Reject.list" ]; then
                    mv ./filter_remote/Reject.list ./bak/Reject.list.bak
                fi

                # 移动文件
                if ! mv ./Reject.list ./filter_remote/Reject.list; then
                    echo "Failed to move the file."
                    exit 1
                fi

                echo "File successfully downloaded, backed up, and moved."
            - name: 更新
              run: |
                git config --local user.email ${{ secrets.EMAIL }}
                git config --local user.name ${{ secrets.NAME }}
                git pull
                git add bak filter_remote version
                git commit -m "Update"
                git push
                
            - name: 发布到release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ env.version }}
                  body_path: bgcode.txt
            - name: 删除
              run: |
                  
                  current_run_id=$(echo "$GITHUB_RUN_ID")
                  
                  runs=$(curl -s -X GET "https://api.github.com/repos/${{ github.repository }}/actions/workflows/my.yml/runs" \
                  
                  -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  
                  -H "Accept: application/vnd.github.v3+json" | jq -r '.workflow_runs[].id')
                  
                  echo "$runs"
                  
                  keep_runs=$(echo "$runs" | head -n 3)
                  
                  for run_id in $runs; do
                  
                  if [ "$run_id" != "$current_run_id" ] && [[ ! "$keep_runs" =~ "$run_id" ]]; then
                  
                  curl -s -X DELETE "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id" \
                  
                  -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  
                  -H "Accept: application/vnd.github.v3+json" > /dev/null
                  
                  fi
                  
                  done